### ISSUE TITLE
新規登録/ログイン画面

### ISSUE THREAD

**Issue by rick1919** [ailab-dev/app_buy_sell#1]
### Design
![スクリーンショット 2024-01-16 17 45 07](https://github.com/ailab-dev/AppBuySell/assets/29033989/dd82d2b4-5c67-4ac9-933c-950b1f1db193)

### Design's link
https://www.figma.com/file/FYxK9KgFf68uS9nUjZoO8V/prodhub-%E3%82%A2%E3%83%97%E3%83%AA?type=design&node-id=939-274&mode=design&t=tGVpt94aQhAJri09-4

**Comment by rick1919** [comment]
@Trangkiai 
こちらissueの粒度大きかったでしょうか！？

今後も1日30%ずつの開発になりますか？

**Comment by Trangkiai** [comment]
@rick1919 
登録とログインとログイン後の情報入力機能を対応するため、
仕事の内容がかなり多いです。
ご理解のほどよろしくお願いいたします。

**Comment by rick1919** [comment]
@Trangkiai 
"かなり多い"というのはどのくらい多いかはわかりませんが以下のやりとりに則ってこのタスクは1週間以内で完了すると認識しておりますのでよろしくお願いいたします。

https://ailab-corp.slack.com/archives/C0301DK1YV8/p1705464783109899

またこちらの期日もMTGで共有したように理解していただきたいです。

**Comment by Trangkiai** [comment]
@rick1919 
はい、かしこまりました。
このタスクは3日間（1月18日,19日,22日）で対応いたします。
何卒宜しくお願い致します。

**Comment by rick1919** [comment]
@Trangkiai 
よろしくお願いします！
完了しましたらpush、PR作成の方を忘れないようお願いします！

**Comment by Trangkiai** [comment]
@mafreud cc @rick1919 
お疲れ様です。
以下のPRを作成致しました。
ご確認いただけますと幸いです。
https://github.com/ailab-dev/app_buy_sell/pull/15

**Comment by rick1919** [comment]
めも：login画面開発完了後merge
