### ISSUE TITLE
設定画面

### ISSUE THREAD

**Issue by rick1919** [ailab-dev/app_buy_sell#10]
### Design
![スクリーンショット 2024-01-16 17 58 40](https://github.com/ailab-dev/AppBuySell/assets/29033989/175be352-aa9c-434e-991e-d9c29767e754)

### Design's link
https://www.figma.com/file/FYxK9KgFf68uS9nUjZoO8V/prodhub-%E3%82%A2%E3%83%97%E3%83%AA?type=design&node-id=944-4359&mode=design&t=tGVpt94aQhAJri09-4
### TODO
- Notion対応
    - 運営からのお知らせ
    - プライバシーポリシー
    - 利用規約
- google form対応
    - お問い合わせ
    - アプリの不具合・改善要望を報告する

**Comment by DuyenTran2209** [comment]
@rick1919  @mafreud 
お疲れ様です。
お問い合わせ画面やプライバシーポリシー画面などKiaiに指定していますが、まだデザインがありませんので、
ご提供のほどよろしくお願いします。

**Comment by rick1919** [comment]
@DuyenTran2209 
webviewの想定です
