### ISSUE TITLE
ホーム(一覧)画面

### ISSUE THREAD

**Issue by rick1919** [ailab-dev/app_buy_sell#2]
### Design
![スクリーンショット 2024-01-16 17 46 24](https://github.com/ailab-dev/AppBuySell/assets/29033989/2da5fe00-26d8-4665-8965-572950fb6361)

### Design's link
https://www.figma.com/file/FYxK9KgFf68uS9nUjZoO8V/prodhub-%E3%82%A2%E3%83%97%E3%83%AA?type=design&node-id=942-2220&mode=design&t=tGVpt94aQhAJri09-4

**Comment by Trangkiai** [comment]
@rick1919 
お疲れ様です。
フォンさんが着手いたしました。
着手するとき、Iterationの方でステータスを定期的に変更するので、ご確認いただけますと幸いです。

**Comment by Trangkiai** [comment]
@mafreud cc @rick1919 
お疲れ様です。
Issueを完了し、PRを作成致しました。
ご確認のほどよろしくお願い申し上げます。
https://github.com/ailab-dev/app_buy_sell/pull/16

**Comment by PhongTaKiai** [comment]
close https://github.com/ailab-dev/app_buy_sell/pull/17
