### ISSUE TITLE
構築をmvvmからriverpodに変更

### ISSUE THREAD

**Issue by Trangkiai** [ailab-dev/app_buy_sell#20]
Related link: https://github.com/ailab-dev/app_buy_sell/pull/15#discussion_r1468273883

**Comment by Trangkiai** [comment]
Tiêu đề: Chuyển cấu trúc từ mvvm sang riverpod
Link liên quan: https://github.com/ailab-dev/app_buy_sell/pull/15#discussion_r1468273883

**Comment by mafreud** [comment]
@Trangkiai, please remove my assignment since this is @PhongTaKiai 's task.
