### ISSUE TITLE
SNSリンクバリデーション[マイページ編集画面]

### ISSUE THREAD

**Issue by rick1919** [ailab-dev/app_buy_sell#29]
### Related Issue
#27

**Comment by DuyenTran2209** [comment]
@PhongTaKiai 
Title: Validation link SNS ( màn hình edit my page) #29

**Comment by DuyenTran2209** [comment]
@rick1919 cc: @mafreud @PhongTaKiai 
お疲れ様です。
このタスクについて確認させていただきます。
デザイン上ではテキスト入力という形ですから、バーリデート不可能です。
どのように対応すれば良いか、具体的にご共有していただければと存じます。

**Comment by rick1919** [comment]
@DuyenTran2209 @PhongTaKiai 
入力したテキストが以下のように表示できるのであれば問題ないです。
もしかしたらバリデーション自体が必要ないかもなので！
![image](https://github.com/ailab-dev/app_buy_sell/assets/29033989/03271440-982f-457d-96de-d8b504c19bf0)

**Comment by rick1919** [comment]
@PhongTaKiai @DuyenTran2209 
Did you understand?

**Comment by DuyenTran2209** [comment]
> @PhongTaKiai @DuyenTran2209 Did you understand?
cc: @PhongTaKiai 
お疲れ様です。
こちらの件について、以前共有下通りに、開発者のフォンが上記のイメージと同様に実装していました。
何か変更すべき箇所があればご指摘のほどよろしくお願いいたします。
