### ISSUE TITLE
プロダクト詳細画面

### ISSUE THREAD

**Issue by rick1919** [ailab-dev/app_buy_sell#3]
### Design
![スクリーンショット 2024-01-16 17 47 07](https://github.com/ailab-dev/AppBuySell/assets/29033989/61005272-4ea7-4cdc-aae3-055ab48cb665)

### Design's link
https://www.figma.com/file/FYxK9KgFf68uS9nUjZoO8V/prodhub-%E3%82%A2%E3%83%97%E3%83%AA?type=design&node-id=1025-97&mode=design&t=tGVpt94aQhAJri09-4

### TODO
- レビューをstoreより取得し出力

**Comment by Trangkiai** [comment]
Dịch:
Lấy レビュー (review) từ store và cho xuất ra.

**Comment by mafreud** [comment]
こちらは一旦手動でよいかと！　@rick1919

**Comment by rick1919** [comment]
@mafreud @Trangkiai 
手動で頑張ります！

**Comment by Trangkiai** [comment]
@rick1919 
はい、かしこまりました！

**Comment by Trangkiai** [comment]
@rick1919 @mafreud 
念のため確認させていただきます。
報告させていただいた通りにAppstoreからレビュー情報を取得できますが、Google Playから情報を取得できないです。
では、Appstoreから直接最新情報を取得し、Google Playの方は手動で入力しますでしょうか？
その場合、Appstoreの情報と手動で入力した情報は相違になる可能性がありますが、いかがでしょうか？

**Comment by rick1919** [comment]
@Trangkiai @mafreud 
でしたら一旦app storeだけの掲載で大丈夫です！

**Comment by Trangkiai** [comment]
Dịch phần Sato san viết: tạm thời chỉ hiển thị phần của appstore thôi.

**Comment by Trangkiai** [comment]
@rick1919 @mafreud 
お疲れ様です。
赤枠の部分の仕様について確認させていただきます。

1. いつ販売が終了になりますでしょうか？
2. バイヤーがアプリを買った後、どう表示しますか？

ご共有いただけますと幸いです。

![image](https://github.com/ailab-dev/app_buy_sell/assets/109328238/8282e38b-18c9-47a3-ae63-5c172f6fe79c)

**Comment by rick1919** [comment]
@Trangkiai @PhongTaKiai 

上記質問共にこちらのissueを見ていただくと理解していただけると思います。
https://github.com/ailab-dev/app_buy_sell/issues/4

>いつ販売が終了になりますでしょうか？
こちらは上記issueの購入完了されたのちに終了のステータスになります。

>バイヤーがアプリを買った後、どう表示しますか？
こちらも上記issueにあるようにしたから出でくるデザインを想定しております。

**Comment by Trangkiai** [comment]
@mafreud cc @rick1919 
タスクのPRを作成致しました。
ご確認いただけますと幸いです。
https://github.com/ailab-dev/app_buy_sell/pull/17
