### ISSUE TITLE
アプリ掲載画面

### ISSUE THREAD

**Issue by rick1919** [ailab-dev/app_buy_sell#33]
### Related Issue
https://github.com/ailab-dev/app_buy_sell/issues/5
### Design
![スクリーンショット 2024-03-12 16 40 36](https://github.com/ailab-dev/app_buy_sell/assets/29033989/fad81771-564b-4ca6-ad2b-459c08ddab90)

### Design's link
https://www.figma.com/file/FYxK9KgFf68uS9nUjZoO8V/prodhub-%E3%82%A2%E3%83%97%E3%83%AA?type=design&node-id=1371-1039&mode=design&t=F77362dNqSeZkxJc-4
### TODO
- プトダクトを登録できる
- storeリンクから情報を取得できる

**Comment by DuyenTran2209** [comment]
@PhongTaKiai 
TODO
Có thể đăng kí product 
Có thể lấy thông tin từ link store

**Comment by DuyenTran2209** [comment]
@rick1919  cc: @PhongTaKiai 
お疲れ様です。
「アプリを掲載する」画面について
「Storeリンク」フィールドのデザインから見ると、IOSのリンクのみを入力するようですが、（添付のスクリーンショットをご参照くださいませ）
こちらはオペレーティング システムに応じて表示されると思いますが、認識合っていますか。
（※IOSと Android の両方対応可能）

![Screenshot 2024-03-18 at 10 57 26](https://github.com/ailab-dev/app_buy_sell/assets/160696494/779522b2-2b7f-4345-88d4-310b1566a8b0)

**Comment by DuyenTran2209** [comment]
@mafreud cc: @PhongTaKiai 
お疲れ様です。
本機能は画像を保存するために、ストレージが必要ですので、firebaseでストレージがオンにしていただければと存じます。
よろしくお願いいたします。

**Comment by mafreud** [comment]
@DuyenTran2209 cc: @PhongTaKiai done 👍
