### ISSUE TITLE
新規アカウント登録画面

### ISSUE THREAD

**Issue by rick1919** [ailab-dev/app_buy_sell#35]
### TODO
新規登録の際のメアドに関して
「メールが使用されました」を「このメールアドレスはすでに登録されています。」 に変更

**Comment by DuyenTran2209** [comment]
@PhongTaKiai 
Về địa chỉ mail address khi đăng kí mới (register) 
Nhờ bạn đổi text メールが使用されました Thành このメールアドレスはすでに登録されています。giúp tôi với ạ
