### ISSUE TITLE
購入画面

### ISSUE THREAD

**Issue by rick1919** [ailab-dev/app_buy_sell#4]
### Design
![スクリーンショット 2024-01-16 17 48 49](https://github.com/ailab-dev/AppBuySell/assets/29033989/a5b69db0-4dbc-4e7c-80fc-9fc0cc652c41)

### Design's link
https://www.figma.com/file/FYxK9KgFf68uS9nUjZoO8V/prodhub-%E3%82%A2%E3%83%97%E3%83%AA?type=design&node-id=941-1879&mode=design&t=tGVpt94aQhAJri09-4

**Comment by Trangkiai** [comment]
@rick1919 
お疲れ様です。
こちらのイラストは具体的に何か、ご共有いただけますでしょうか？
お手数をおかけしますが、よろしくお願いいたします。
![image](https://github.com/ailab-dev/app_buy_sell/assets/109328238/234aa750-cf96-4ccb-8a58-2c48cfbfddd2)

**Comment by rick1919** [comment]
@Trangkiai @harukamochizuki 
確かに抜けてましたね！

望月さんこちらお願いしてもよろしいでしょうか！？

**Comment by Trangkiai** [comment]
@mafreud cc @rick1919
タスクのPRを作成致しました。
ご確認いただけますと幸いです。
https://github.com/ailab-dev/app_buy_sell/pull/22
