### ISSUE TITLE
ApplePayで購入できる

### ISSUE THREAD

**Issue by rick1919** [ailab-dev/app_buy_sell#40]
### Related Issue
https://github.com/ailab-dev/app_buy_sell/pull/22

**Comment by DuyenTran2209** [comment]
@PhongTaKiai 
Title: Có thể mua trên ApplePay

**Comment by rick1919** [comment]
弊社のappleアカウントに入金されるようにする

**Comment by DuyenTran2209** [comment]
@PhongTaKiai 
Anh Sato cmt là nhờ mình đối ứng sao cho tiền sẽ thanh toán vào account apple bên họ ạ

**Comment by rick1919** [comment]
sandboxアカウント待ち
