### ISSUE TITLE
実機テストできるようにする

### ISSUE THREAD

**Issue by rick1919** [ailab-dev/app_buy_sell#42]
### TODO
以下メール宛に実機テストのアプリ配布お願いします。
r.sato@ailab-corp.com

**Comment by DuyenTran2209** [comment]
@PhongTaKiai 
E dịch nội dung trên ạ 
Nhờ bạn đối ứng sao cho gửi app test thực tế tới địa chỉ email bên dưới ạ 
[r.sato@ailab-corp.com](mailto:r.sato@ailab-corp.com)
