### ISSUE TITLE
アプリ掲載画面(webview)

### ISSUE THREAD

**Issue by rick1919** [ailab-dev/app_buy_sell#5]
### Design
![スクリーンショット 2024-01-16 17 49 51](https://github.com/ailab-dev/AppBuySell/assets/29033989/76dff3c0-54e4-4e2d-9878-eea517bcac9e)

### Design's link
https://www.figma.com/file/FYxK9KgFf68uS9nUjZoO8V/prodhub-%E3%82%A2%E3%83%97%E3%83%AA?type=design&node-id=1279-1344&mode=design&t=tGVpt94aQhAJri09-4
### TODO
- "アプリ掲載をする"をタップするとgoogle formがwebviewがでてきてそこからプロダクト登録ができる形

**Comment by Trangkiai** [comment]
@rick1919 @mafreud 
お世話になっております。
以下のPRを作成致しました。
ご確認願えますと幸いです。
https://github.com/ailab-dev/app_buy_sell/pull/23
