### ISSUE TITLE
通知画面

### ISSUE THREAD

**Issue by rick1919** [ailab-dev/app_buy_sell#6]
### Design
![スクリーンショット 2024-01-16 17 51 35](https://github.com/ailab-dev/AppBuySell/assets/29033989/f11cbb6a-0e31-46e2-b927-ae6648f297c6)

### Design's link
https://www.figma.com/file/FYxK9KgFf68uS9nUjZoO8V/prodhub-%E3%82%A2%E3%83%97%E3%83%AA?type=design&node-id=998-4662&mode=design&t=tGVpt94aQhAJri09-4
### TODO
**通知タイミング**
- プロダクト掲載時
- プロダクト売買成立時

**Comment by Trangkiai** [comment]
@rick1919 cc @mafreud 
お世話になっております。
本機能を対応するために、Cloud Functionを利用するので、クレジットカードでの支払いが必要です。
ご確認いただきますようお願い申し上げます。

**Comment by rick1919** [comment]
> @rick1919 cc @mafreud お世話になっております。 本機能を対応するために、Cloud Functionを利用するので、クレジットカードでの支払いが必要です。 ご確認いただきますようお願い申し上げます。

かしこまりました！
リンクいただくことは可能でしょうか！？

**Comment by rick1919** [comment]
@Trangkiai @PhongTaKiai

**Comment by Trangkiai** [comment]
@rick1919 
お疲れ様です。
リンクをお送りいたします。
https://console.firebase.google.com/project/app-buy-sell-prod/functions
「upgrade project」というところのご確認お願い致します。

**Comment by rick1919** [comment]
@PhongTaKiai @DuyenTran2209 
すみません。
こちら僕のせいでpenddingになっておりましたね。
カード登録済なのでrestartお願いします。
https://github.com/ailab-dev/app_buy_sell/pull/24

**Comment by DuyenTran2209** [comment]
@PhongTaKiai cc: @rick1919 
Anh ơi anh Sato có cmt ạ 
Do bên tôi nên task này bị pendding 
Tôi đã đăng kí card xong rồi nhờ bên bạn restart ạ
