### ISSUE TITLE
他人のプロフィール画面

### ISSUE THREAD

**Issue by rick1919** [ailab-dev/app_buy_sell#7]
### Design
![スクリーンショット 2024-01-16 17 55 37](https://github.com/ailab-dev/AppBuySell/assets/29033989/1ff00302-7fc5-4c00-b98d-89a50cab97f2)

### Design's link
https://www.figma.com/file/FYxK9KgFf68uS9nUjZoO8V/prodhub-%E3%82%A2%E3%83%97%E3%83%AA?type=design&node-id=943-3750&mode=design&t=tGVpt94aQhAJri09-4

**Comment by DuyenTran2209** [comment]
@mafreud  cc: @rick1919 
こちらのタスクのPRを作成致しました。
お手すきの際にご確認いただけますと幸いです。
#25
