### ISSUE TITLE
マイプロフィール表示画面

### ISSUE THREAD

**Issue by rick1919** [ailab-dev/app_buy_sell#8]
### Related Issue
UIほぼ一緒
https://github.com/ailab-dev/AppBuySell/issues/7

### Design
![スクリーンショット 2024-01-16 17 56 35](https://github.com/ailab-dev/AppBuySell/assets/29033989/d0b1ea7c-8db6-4edc-9c52-3e6f21c28b41)

### Design's link
https://www.figma.com/file/FYxK9KgFf68uS9nUjZoO8V/prodhub-%E3%82%A2%E3%83%97%E3%83%AA?type=design&node-id=959-329&mode=design&t=tGVpt94aQhAJri09-4

**Comment by DuyenTran2209** [comment]
@mafreud  cc: @rick1919 
こちらのタスクのPRを作成致しました。
お手すきの際にご確認いただけますと幸いです。
#26
